import NavBar from "@/components/Nav/NavBar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Zipco Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-full h-auto">
          <NavBar></NavBar>
        {children}
        </div>
      </body>
    </html>
  );
}
